#!/bin/sh -e
# Copyright 2019 Branen Salmon
# Licensed under the GNU GPL v3 or later--see LICENSE for details.
SV_BASE='([0-9]+\.){2}[0-9]+'
SV_ID='[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*'
SV_WHOLE="${SV_BASE}(-${SV_ID})?(\\+${SV_ID})?"
NAME=pass-dmenu

explicit=''
cwd="$(pwd)"
cd "$(dirname "$0")"
if [ $# -eq 0 ]
then
    tag=''
    while [ -z "${tag##*/*}" ]
    do
        if [ -z "$tag" ]
        then
            tag='HEAD'
        else
            tag="$tag~1"
        fi
        tag="$(git describe --abbrev=0 "$tag")"
    done
else
    tag="$1"
    explicit=y
fi
if ! printf '%s\n' "$tag" | grep -q -E -e "v$SV_WHOLE"
then
    cat >&2 <<EOF
ERROR: Tags must be of the form "v\$SEMVER", where \$SEMVER is a valid
Semantic Versioning 2.0.0 expression.
"$tag" does not conform to this requirement.
EOF
    exit 1
fi
if ! git tag -v "$tag" 1>/dev/null 2>/dev/null
then
    echo "Could not verify signature on $tag." >&2
    exit 1
fi
rev="$(git rev-parse "refs/tags/$tag^{commit}")"
if [ -z "$explicit" -a ".$rev" != ".$(git rev-parse 'HEAD^{commit}')" ]
then
    echo "WARNING: Exporting $tag, which is not the same as HEAD." >&2
fi
version="${tag#v}"
target="../${NAME}_$version.orig.tar.xz"
GIT_CONFIG=git-archive.cfg \
    git archive --prefix="$NAME-$version/" "$rev" | xz >"$target"

realpath --relative-to="$cwd" "$target"
