The HTML manual looks much better with the following fonts:

Font name          | CTAN package | Debian package
-------------------+--------------+--------------------------
Bitstream Charter  | charter      | texlive-fonts-recommended
Latin Modern Mono  | lm           | fonts-lmodern


It requires Pandoc and Panflute to build:

https://pandoc.org/
http://scorreia.com/software/panflute/
